### ISSUE TITLE
1.20.x Support

### ISSUE THREAD

**Issue by Colusite** [SaitDev/MobArenaExtension#34]
The plugin currently does not work for versions 1.20 and 1.20.1

You cannot put MythicMobs as mobs in the configuration file.

**Comment by SaitDev** [comment]
@Colusite pls have a try https://github.com/SaitDev/MobArenaExtension/actions/runs/6793400169

**Comment by PrinceOfIonia** [comment]
@SaitDev, unfortunately the new build doesn't work for me on 1.20.2.

**Comment by SaitDev** [comment]
@PrinceOfIonia could u give some details, do u see any error in console log?

**Comment by PrinceOfIonia** [comment]
> @PrinceOfIonia could u give some details, do u see any error in console log?

Didn't see this for some reason, I checked the debug and everything, I got no warnings in the console from what I can tell, but MobArena just complains that it doesn't register the MythicMob as a valid mob type

I see MobArenaExtension loading up in the console though, I could try and search again to see if I find something specific.

**Comment by SaitDev** [comment]
I couldnt reproduce issue on 1.20.1 and 1.20.2. 
Close due to inactivity. 
If you somehow face this issue again on 1.20, feel free to open new ticket

**Comment by Khotul** [comment]
I believe the issue OP stumbled upon was `java.lang.NoSuchFieldError: Class io.lumine.mythic.api.mobs.entities.MythicEntityType does not have member field 'io.lumine.mythic.api.mobs.entities.MythicEntityType PIG_ZOMBIE'`

From what I can tell this was fixed in #37 PR, however plugin version with this fix isn't available for download without compiling it manually, which is a pain for users that aren't knowledgable. 

The Artifacts pushed by Github Actions expire after some time, as did this one, so the only way to get a version working for 1.20.x is by building it.

**Comment by SaitDev** [comment]
@Khotul for the issue that Colusite mentioned it was updated for MythicMobs 5.4 before [95dd9b567ffe97a1e0b6fa8280850a19bf22c08b](https://github.com/SaitDev/MobArenaExtension/commit/95dd9b567ffe97a1e0b6fa8280850a19bf22c08b), not the recently PR 
what i couldnt reproduce is the issue that PrinceOfIonia somehow had it

But its right the fix is not released yet and snapshot builds expired few days ago. I'll public one this month after getting some free time, been busy IRL lately
